In [44]:
#Importing necessary modules to do the visualization
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [45]:
#Read the dataset
df=pd.read_csv("train.csv")

In [46]:
#Viewing the dataset from the top
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [47]:
df.shape

(2183, 81)

In [48]:
#Finding number of parameters, datatypes nad null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2183 entries, 0 to 2182
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2183 non-null   int64
 1   MSSubClass     2183 non-null   int64
 2   MSZoning       2179 non-null   object
 3   LotFrontage    1818 non-null   float64
 4   LotArea        2183 non-null   int64
 5   Street         2183 non-null   object
 6   Alley          148 non-null    object
 7   LotShape       2183 non-null   object
 8   LandContour    2183 non-null   object
 9   Utilities      2181 non-null   object
 10  LotConfig      2183 non-null   object
 11  LandSlope      2183 non-null   object
 12  Neighborhood   2183 non-null   object
 13  Condition1     2183 non-null   object
 14  Condition2     2183 non-null   object
 15  BldgType       2183 non-null   object
 16  HouseStyle     2183 non-null   object
 17  OverallQual    2183 non-null   int64
 18  OverallCond    2183 non-null   int64
 19  YearBuilt      2183 non-null   int64
 20  YearRemodAdd   2183 non-null   int64
 21  RoofStyle      2183 non-null   object
 22  RoofMatl       2183 non-null   object
 23  Exterior1st    2182 non-null   object
 24  Exterior2nd    2182 non-null   object
 25  MasVnrType     861 non-null    object
 26  MasVnrArea     2167 non-null   float64
 27  ExterQual      2183 non-null   object
 28  ExterCond      2183 non-null   object
 29  Foundation     2183 non-null   object
 30  BsmtQual       2121 non-null   object
 31  BsmtCond       2121 non-null   object
 32  BsmtExposure   2121 non-null   object
 33  BsmtFinType1   2123 non-null   object
 34  BsmtFinSF1     2182 non-null   float64
 35  BsmtFinType2   2122 non-null   object
 36  BsmtFinSF2     2182 non-null   float64
 37  BsmtUnfSF      2182 non-null   float64
 38  TotalBsmtSF    2182 non-null   float64
 39  Heating        2183 non-null   object
 40  HeatingQC      2183 non-null   object
 41  CentralAir     2183 non-null   object
 42  Electrical     2183 non-null   object
 43  1stFlrSF       2183 non-null   int64
 44  2ndFlrSF       2183 non-null   int64
 45  LowQualFinSF   2183 non-null   int64
 46  GrLivArea      2183 non-null   int64
 47  BsmtFullBath   2181 non-null   float64
 48  BsmtHalfBath   2181 non-null   float64
 49  FullBath       2183 non-null   int64
 50  HalfBath       2183 non-null   int64
 51  BedroomAbvGr   2183 non-null   int64
 52  KitchenAbvGr   2183 non-null   int64
 53  KitchenQual    2182 non-null   object
 54  TotRmsAbvGrd   2183 non-null   int64
 55  Functional     2182 non-null   object
 56  Fireplaces     2183 non-null   int64
 57  FireplaceQu    1105 non-null   object
 58  GarageType     2057 non-null   object
 59  GarageYrBlt    2055 non-null   float64
 60  GarageFinish   2055 non-null   object
 61  GarageCars     2182 non-null   float64
 62  GarageArea     2182 non-null   float64
 63  GarageQual     2055 non-null   object
 64  GarageCond     2055 non-null   object
 65  PavedDrive     2183 non-null   object
 66  WoodDeckSF     2183 non-null   int64
 67  OpenPorchSF    2183 non-null   int64
 68  EnclosedPorch  2183 non-null   int64
 69  3SsnPorch      2183 non-null   int64
 70  ScreenPorch    2183 non-null   int64
 71  PoolArea       2183 non-null   int64
 72  PoolQC         5 non-null      object
 73  Fence          430 non-null    object
 74  MiscFeature    88 non-null     object
 75  MiscVal        2183 non-null   int64
 76  MoSold         2183 non-null   int64
 77  YrSold         2183 non-null   int64
 78  SaleType       2183 non-null   object
 79  SaleCondition  2183 non-null   object
 80  SalePrice      986 non-null    float64
dtypes: float64(12), int64(26), object(43)
memory usage: 1.3+ MB

In [49]:
#Finding statistical parameters
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,2183.000000,2183.000000,1818.000000,2183.000000,2183.000000,2183.000000,2183.000000,2183.000000,2167.000000,2182.000000,...,2183.000000,2183.000000,2183.00000,2183.000000,2183.000000,2183.000000,2183.000000,2183.000000,2183.000000,986.00000
mean,1398.954650,58.041686,68.966997,10224.989464,6.085662,5.563903,1971.246450,1984.120018,104.223812,444.184693,...,95.414567,47.656894,23.86853,2.795236,16.322950,1.325240,57.238204,6.184608,2007.892350,181973.38641
std,907.707977,43.122846,22.855051,8633.995607,1.414048,1.112144,30.149744,20.846220,183.813980,452.452889,...,127.754505,68.144143,63.22525,26.250603,56.855782,27.958781,623.132890,2.695738,1.355253,80124.49498
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1880.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.00000
25%,546.500000,20.000000,59.000000,7402.000000,5.000000,5.000000,1953.000000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,130000.00000
50%,1566.000000,50.000000,68.000000,9392.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,374.000000,...,0.000000,26.000000,0.00000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.00000
75%,2111.500000,70.000000,80.000000,11554.500000,7.000000,6.000000,2000.000000,2003.000000,168.000000,740.500000,...,168.000000,71.000000,0.00000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,215000.00000
max,2919.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,4010.000000,...,1424.000000,742.000000,584.00000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.00000

In [50]:
#Finding is there any null values are present in the dataset or not
df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       365
LotArea             0
                 ...
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice        1197
Length: 81, dtype: int64

In [52]:
df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       365
LotArea             0
                 ...
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice        1197
Length: 81, dtype: int64

In [53]:
y=df['SalePrice']
X=df.drop(columns=['SalePrice', 'Id'])

In [54]:
num = X.select_dtypes(include=['number']).columns
cat = X.select_dtypes(include=['object']).columns

In [55]:
import pandas as pd
from sklearn.impute import SimpleImputer

# Assuming X is your DataFrame
num = X.select_dtypes(include=['number']).columns
cat = X.select_dtypes(include=['object']).columns

# Impute missing values in numerical columns with the median
imputer_num = SimpleImputer(strategy='median')
X[num] = imputer_num.fit_transform(X[num])

# Alternatively, impute missing values in numerical columns with the mean
# X[num] = X[num].fillna(X[num].mean())

# Impute missing values in categorical columns with the most frequent value
imputer_cat = SimpleImputer(strategy='most_frequent')
X[cat] = imputer_cat.fit_transform(X[cat])

In [56]:
from sklearn.preprocessing import StandardScaler

# Standardize numerical features
scaler = StandardScaler()
X[num] = scaler.fit_transform(X[num])

In [57]:
# One-hot encode categorical features
X = pd.get_dummies(X, columns=cat)

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=42)